# Version: 1.0.6
services:
  piloto-financiero:
    build:
      context: .
      args:
        - BUILD_VERSION=1.0.6
    container_name: piloto-financiero
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1  # No buffear salida de Python para ver logs en tiempo real
      - DEBUG_LOG=true  # Habilitar/deshabilitar logs de debug (true/false)
      - TZ=Europe/Madrid  # Zona horaria (ajustar si es diferente)
    restart: unless-stopped