# Version: 1.0.0
services:
  piloto-financiero:
    build:
      context: .
      args:
        - BUILD_VERSION=1.0.0
    container_name: piloto-financiero
    ports:
      - "5000:5000"
    restart: unless-stopped